services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # Cổng cho service RabbitMQ
      - "15672:15672"     # Cổng cho web management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge