# .github/workflows/deploy-to-render.yml
name: CI/CD to Render

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js & cache Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install & Build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test -- --runInBand

      - name: Deploy to Render
        if: github.event_name == 'push'  
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Accept: application/json"
