# .github/workflows/deploy-to-render.yml
name: CI/CD to Render

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code (kéo luôn tags về)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js & cache Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install & Build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy to Render
        if: github.event_name == 'push'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Accept: application/json"

      - name: Bump version
        id: bump
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # npm version patch sẽ tạo tag vX.Y.Z
          NEW_TAG=$(npm version patch -m "chore(release): bump version to %s")
          # Xuất output để các step sau dùng
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          # Đẩy cả commit và tag lên
          git push origin HEAD:master --follow-tags

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          # Tham chiếu đúng tới output từ step bump
          tag_name: ${{ steps.bump.outputs.NEW_TAG }}
          release_name: Release ${{ steps.bump.outputs.NEW_TAG }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update badges in README
        if: github.event_name == 'push'
        run: |
          VERSION=$(node -p "require('./package.json').version")
          VERSION_BADGE="https://img.shields.io/badge/version-${VERSION}-blue.svg"
          RELEASE_BADGE="https://img.shields.io/badge/release-${VERSION}-green.svg"
          RELEASE_LINK="https://github.com/${{ github.repository }}/releases/tag/${VERSION}"

          sed -i.bak -E \
            "s|(<!-- VERSION BADGE -->).*|\1 ![version](${VERSION_BADGE})|" \
            README.md
          sed -i.bak -E \
            "s|(<!-- RELEASE BADGE -->).*|\1 [![release](${RELEASE_BADGE})](${RELEASE_LINK})|" \
            README.md

          git add README.md
          git commit -m "chore: update badges to v${VERSION}"
          git push origin HEAD:master
